### ISSUE TITLE
SplashScreen during LoginScreen to MainScreen transition.

### ISSUE THREAD

**Issue by HelmerBarcos** [shubhnik/redux-react-navigation-demos#5]
hi! in my code, after the user successfully log in apears the mainSreen, but if the user close the App and then open it again, comes for a few miliseconds the LoginScreen. do you know  how to correct that problem?

kind Regards 

Helmer

**Comment by shubhnik** [comment]
You have to display some other screen(eg splashscreen) while the app looks for whether the person is logged in. I am displaying a simple `Loading...` text in the demo. You can display some screen instead of that `loading...` text.
